# Generated by Django 4.2.3 on 2023-07-11 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retent_restful', '0003_rename_emailaddress_user_email_user_groups_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='emailAddress',
        ),
        migrations.AddField(
            model_name='user',
            name='kakao_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
